version: '3.8'
services:
  app:
    image: php:8.1-apache
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - 5432:5432

volumes:
  db_data:

networks:
  laravel:
